# Generated by Django 5.2.6 on 2025-09-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceiros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terceiro',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='terceiro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='terceiro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='terceiro',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='terceiro',
            name='estado',
        ),
    ]
