# Generated by Django 5.2.6 on 2025-09-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceiros', '0002_remove_terceiro_cep_remove_terceiro_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceiro',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
