# Generated by Django 5.2.6 on 2025-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0002_auto_20250913_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
