# Generated by Django 5.2.6 on 2025-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0003_cidade_updated_at_estado_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
