# Generated by Django 5.2.6 on 2025-09-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('filtros', models.JSONField(help_text='Filtros aplicados ao relatório')),
                ('campos_exibidos', models.JSONField(help_text='Campos a serem exibidos')),
                ('descricao', models.TextField(blank=True)),
                ('publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relatório Personalizado',
                'verbose_name_plural': 'Relatórios Personalizados',
                'ordering': ['nome'],
            },
        ),
    ]
