# Generated by Django 5.2.6 on 2025-09-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatorioPersonalizado',
        ),
    ]
