# Generated by Django 5.2.6 on 2025-09-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_initial'),
    ]

    operations = [
    ]
