# Generated by Django 5.2.6 on 2025-09-09 23:00

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('em_revisao', 'Em Revisão')], max_length=15)),
                ('status_novo', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('em_revisao', 'Em Revisão')], max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Validação',
                'verbose_name_plural': 'Históricos de Validação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPrestacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario_chegada', models.TimeField()),
                ('horario_saida_almoco', models.TimeField(blank=True, null=True)),
                ('horario_retorno_almoco', models.TimeField(blank=True, null=True)),
                ('horario_saida', models.TimeField()),
                ('validacao_local', models.BooleanField(default=False, help_text='Validação no local da prestação')),
                ('validacao_gestor', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('em_revisao', 'Em Revisão')], default='pendente', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da prestação de serviço', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observacoes', models.TextField(blank=True)),
                ('foto_comprovante', models.ImageField(blank=True, null=True, upload_to='prestacoes/%Y/%m/')),
                ('latitude_chegada', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude_chegada', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('latitude_saida', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude_saida', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Prestação',
                'verbose_name_plural': 'Registros de Prestação',
                'ordering': ['-data', '-horario_chegada'],
            },
        ),
    ]
