# Generated by Django 5.2.6 on 2025-09-09 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('funcionarios', '0002_initial'),
        ('localizacao', '0001_initial'),
        ('prestacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicovalidacao',
            name='validado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroprestacao',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroprestacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='registroprestacao',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_supervisionadas', to='empresas.gestor'),
        ),
        migrations.AddField(
            model_name='registroprestacao',
            name='local_prestacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes', to='localizacao.localprestacao'),
        ),
        migrations.AddField(
            model_name='historicovalidacao',
            name='prestacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_validacoes', to='prestacoes.registroprestacao'),
        ),
        migrations.AddIndex(
            model_name='registroprestacao',
            index=models.Index(fields=['funcionario', 'data'], name='prestacoes__funcion_04c36c_idx'),
        ),
        migrations.AddIndex(
            model_name='registroprestacao',
            index=models.Index(fields=['local_prestacao', 'data'], name='prestacoes__local_p_051689_idx'),
        ),
        migrations.AddIndex(
            model_name='registroprestacao',
            index=models.Index(fields=['gestor', 'validacao_gestor'], name='prestacoes__gestor__cca889_idx'),
        ),
        migrations.AddIndex(
            model_name='registroprestacao',
            index=models.Index(fields=['data'], name='prestacoes__data_ffd69b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registroprestacao',
            unique_together={('funcionario', 'data', 'local_prestacao')},
        ),
    ]
