# Generated by Django 5.2.6 on 2025-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes', '0003_auto_20250913_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicovalidacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
