# Generated by Django 5.2.6 on 2025-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
