# Generated by Django 5.2.6 on 2025-09-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Foto do funcionário no momento do ponto', upload_to='pontos/%Y/%m/')),
                ('ip', models.CharField(help_text='IP do dispositivo no momento do registro', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude do local do ponto', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude do local do ponto', max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora do registro do ponto')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(help_text='Funcionário que realizou o ponto', on_delete=django.db.models.deletion.PROTECT, related_name='pontos', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-created_at'],
            },
        ),
    ]
